In [1]:
#importando bibliotecas
import pandas as pd

In [13]:
#carregando planilha com os dados
db = pd.read_csv("Cadastro Escolas 2017.csv", sep=';', engine='python')
#db = pd.read_excel('Cadastro Escolas 2017 Sep.xlsx')
db.head()

,NU_ANO_CENSO,NO_REGIAO,SG_UF,CO_UF,NO_MUNICIPIO,CO_MUNICIPIO,NO_MESORREGIAO,CO_MESORREGIAO,NO_MICRORREGIAO,CO_MICRORREGIAO,...,MAT_EJA,EJA_MAT_FUND,EJA_MAT_MED,EJA_PROF,ESC_ESP,TOTALESP,ESC_ESP_CLASS_COM,ESP_MAT_CLASS_COM,ESC_EXC,MAT_EXC
0,2017,Norte,RO,11,Alta Floresta D'Oeste,1100015,Leste Rondoniense,1102,Cacoal,11006,...,0,0,0,0,0,0.0,0,0,0,0
1,2017,Norte,RO,11,Alta Floresta D'Oeste,1100015,Leste Rondoniense,1102,Cacoal,11006,...,377,174,203,0,1,2.0,1,2,0,0
2,2017,Norte,RO,11,Alta Floresta D'Oeste,1100015,Leste Rondoniense,1102,Cacoal,11006,...,0,0,0,0,0,0.0,0,0,0,0
3,2017,Norte,RO,11,Alta Floresta D'Oeste,1100015,Leste Rondoniense,1102,Cacoal,11006,...,0,0,0,0,1,3.0,1,3,0,0
4,2017,Norte,RO,11,Alta Floresta D'Oeste,1100015,Leste Rondoniense,1102,Cacoal,11006,...,0,0,0,0,1,4.0,1,4,0,0

In [14]:
#analisando a estrutura da planilha
print(db.shape)
max(db.isnull().sum()/len(db))

(184145, 197)

0.997979852833365

In [4]:
print(db.isnull().sum())

NU_ANO_CENSO                        0
NO_REGIAO                           0
SG_UF                               0
CO_UF                               0
NO_MUNICIPIO                        0
CO_MUNICIPIO                        0
NO_MESORREGIAO                      0
CO_MESORREGIAO                      0
NO_MICRORREGIAO                     0
CO_MICRORREGIAO                     0
Localização                         0
LOC_DIF                             0
Rede                                0
CAT_ESC_PRIVADA                144117
NO_ENTIDADE                         0
CO_ENTIDADE                         0
DS_ENDERECO                         0
NU_ENDERECO                     41728
DS_COMPLEMENTO                 121834
NO_BAIRRO                       27257
CO_CEP                              0
CONV_PP                        144117
TIPOCONV                       174619
IN_EDUCACAO_INDIGENA                0
TP_INDIGENA_LINGUA             180840
CO_LINGUA_INDIGENA             181772
IN_MATERIAL_ESP_QUILOMBOLA          0
IN_MATERIAL_ESP_INDIGENA            0
IN_MATERIAL_ESP_NAO_UTILIZA         0
IN_MANT_ESCOLA_PRIVADA_EMP     144117
                                ...
MAT_MED_4_INT                       0
MAT_MED_INT_NS                      0
ESC_MED_NM                          0
MAT_MED_NM                          0
MAT_MED_1_NM                        0
MAT_MED_2_NM                        0
MAT_MED_3_NM                        0
MAT_MED_4_NM                        0
ESC_PROF                            0
MAT_PROF                            0
PROF_TECNICA                        0
PROF_CONC_TEC                       0
PROF_SUBS_TEC                       0
PROF_EJA_TEC_MED                    0
FIC-PROJOVEM                        0
PROF_FIC_CONC                       0
PROF_EJA_PROJOVEM                   0
PROF_EJA_FIC_FUND                   0
PROF_EJA_FIC_MED                    0
ESC_EJA                             0
MAT_EJA                             0
EJA_MAT_FUND                        0
EJA_MAT_MED                         0
EJA_PROF                            0
ESC_ESP                             0
TOTALESP                            0
ESC_ESP_CLASS_COM                   0
ESP_MAT_CLASS_COM                   0
ESC_EXC                             0
MAT_EXC                             0
Length: 197, dtype: int64